### ISSUE TITLE
2 images in cats and dog dataset are corrupt

### ISSUE THREAD

**Issue by pagdot** [vergeml/vergeml#9]
I have the issue that 2 images in the cat and dog dataset are corrupt. I'm not sure if this issuye belong here but I'm not able to complete the Quickstart because of that. The following files are corrupt (empty files):

- cats/666.jpg
- dogs/11702.jpg

Both files are empty and training the files causes errors.

**Comment by mme** [comment]
This is a bug, the download script should have deleted these images.

To continue with the quickstart, you can simply delete the images.

**Comment by pagdot** [comment]
I think it was a problem with my system and not vergeML. My pip installation was broken too and I've got an error on downloading the samples:

```
$ ml download:cats-and-dogs
Downloading cats and dogs to samples.
catsdogs.zip|██████████████████████████████████████| 786 MB, 8162 KB/s
Extracting data.
Traceback (most recent call last):
  File "/home/paul/.local/bin/ml", line 11, in <module>
    sys.exit(main())
  File "/home/paul/.local/lib/python3.6/site-packages/vergeml/__main__.py", line 281, in main
    run(argv, plugins=plugins)
  File "/home/paul/.local/lib/python3.6/site-packages/vergeml/__main__.py", line 221, in run
    return plugin(args, env)
  File "/home/paul/.local/lib/python3.6/site-packages/vergeml/commands/download.py", line 21, in __call__
    plugin(args, env)
  File "/home/paul/.local/lib/python3.6/site-packages/vergeml/datasets/cats_and_dogs.py", line 51, in __call__
    shutil.copytree(os.path.join(src_dir, file), os.path.join(samples_dir, dest))
  File "/usr/lib/python3.6/shutil.py", line 359, in copytree
    raise Error(errors)
shutil.Error: [('.cache/tmp_23430299-c9a6-4261-a9f8-02b820c1ef53/PetImages/Dog', 'samples/dog', "[Errno 13] Permission denied: 'samples/dog'")]
```

**Comment by mme** [comment]
Thanks for the info, closing.
